### PR TITLE
Fix #24 -- Move config to pyproject.toml

### LINKED ISSUE #24: alter PackageSchema
Hi there,

I found the package schema a bit confusing when adding multiple packages.

Currently, I'd have to do something like this:
```toml
[[packages]]
name = "htmx.org"
source = "htmx.org@1.9.8"
[[packages]]
lit = "lit"
source = "lit@3.0.2"
```

Yet, from Pipenv or Poetry I am more used to something like this:

```toml
[[packages]]
htmx.org = "1.9.8"
lit = "3.0.2"
```

Maybe this is worth a consideration. I know it's a backwards incompatible change, but since this package is in its early days, this could be the perfect time to do such alterations.

Cheers!
Joe

### PR DESCRIPTION
**Pull request by codingjoe**
The python community has widely adopeted PIP 621. Therefore, it seems the best place to implement it in this package too.

There are two key changes:

1. The config moves to `tool.importmap`.
2. The importmap config allows adding multiple entries.

Additionally, this commits removes two dependencies:
* marshmellow
* tomli (python_version>=12.0)

Fix #24

### CODE REVIEW

**Comment by codingjoe** [comment]
@davegaeddert I have it a try, hope you like it 👍 I tried to keep it as simple as possible.
The README file, is a probably good place to start reviewing this patch.

**Review by davegaeddert — APPROVED** [review]
Thanks @codingjoe! I'm good with going this direction, and I like the way you did it.

**Comment by davegaeddert** [comment]
Just released this as version 0.3.0.

**Comment by codingjoe** [comment]
Woop, woop 🙌 Thanks! I am very keen on pushing this forward. I believe the concept is a big step forward for Django projects. If you don't mind, I would spend the weekend on mapping out a couple more suggestions to further push this package towards wider adoption. I'd probably start with adding some more documentation and technical writing. Is that cool with you?

**Comment by davegaeddert** [comment]
Yeah I'm happy to look at whatever! No promises on getting it in obviously, but it seems like we're aligned for the most part. Let me know what you're thinking and I'll try to be responsive.

(FWIW I'd prefer docs to be in markdown vs rst — I have no interest in sphinx.)

Honestly the biggest thing I'm personally interested in is "vendoring" (downloading) the dependencies instead of just linking to the CDNs. I know importmap-rails has that as an option, and I think talked about making that the default behavior (or maybe they even changed it?). Anyway, the more I've used it, the more I've wanted it to just work that way. Bigger question/project, but throwing it out there if you're going to be thinking about things.

**Comment by codingjoe** [comment]
> Yeah I'm happy to look at whatever! No promises on getting it in obviously, but it seems like we're aligned for the most part. Let me know what you're thinking and I'll try to be responsive.

No worries, I also reject 2/3 of all proposals on my projects. Good maintenance requires vision 👍 
> 
> (FWIW I'd prefer docs to be in markdown vs rst — I have no interest in sphinx.)

Same here 😉 

> 
> Honestly the biggest thing I'm personally interested in is "vendoring" (downloading) the dependencies instead of just linking to the CDNs. I know importmap-rails has that as an option, and I think talked about making that the default behavior (or maybe they even changed it?). Anyway, the more I've used it, the more I've wanted it to just work that way. Bigger question/project, but throwing it out there if you're going to be thinking about things.


Yes, vendoring, local/offline development, dependabot updates. I will collect my thoughts in separate issues 🤓

**Comment by codingjoe** [comment]
Hello again 👋,

I took some time to rethink the entire concept and ended up implementing an entirely different approach from scratch that addresses my previous concerns.

I chose to do this as part of a new project because entirely different implementation while achieving a similar goal. I just published it here: https://github.com/codingjoe/django-esm

If you are interested in merging those projects and combining efforts, please let me know.

Cheers,
Joe

**Comment by davegaeddert** [comment]
Thanks @codingjoe! To be honest, I don't have time at the moment to think this all the way through, but I'll definitely take a closer look at your approach when I come back to this.

**Pull request merged**
